CREATE DATABASE Bakery;

CREATE TABLE PRODUCT
(
 PR_ID INT(5) PRIMARY KEY,
 PR_NAME VARCHAR(25),
 PR_PRICE INT(10),
 PR_STATUS VARCHAR(25)
);

INSERT INTO PRODUCT VALUES(1,"STRAWBERRY CAKE",350,"AVAILABLE");
INSERT INTO PRODUCT VALUES(2,"CHOCOLATE CAKE",475,"AVAILABLE");
INSERT INTO PRODUCT VALUES(3,"VANILA CAKE",350,"AVAILABLE");
INSERT INTO PRODUCT VALUES(4,"BLACK FOREST CAKE",450,"AVAILABLE");
INSERT INTO PRODUCT VALUES(5,"RED VELVET CAKE",750,"AVAILABLE");
INSERT INTO PRODUCT VALUES(6,"CHOCOLATE PASTRY",30,"AVAILABLE");
INSERT INTO PRODUCT VALUES(7,"VANILA PASTRY",25,"AVAILABLE");
INSERT INTO PRODUCT VALUES(8,"RED VELVET DONUT",35,"AVAILABLE");
INSERT INTO PRODUCT VALUES(9,"PINEAPPLE CAKE",350,"AVAILABLE");
INSERT INTO PRODUCT VALUES(10,"CUP CAKE",15,"AVAILABLE");
INSERT INTO PRODUCT VALUES(11,"STRAWBERRY PASTRY",25,"AVAILABLE");
